[project]
name = "OTS-EventCalendar-Plugin"
description = "Calendario eventi con RSVP, conferma presenze sul campo, punteggi e gradi militari per OpenTAKServer"
authors = [{name = "Andrea Novati", email = "email@nov41337.online"}]
readme = "README.md"
license = "GPL-3.0-or-later"
repository = "https://github.com/novatia/atakcivsaas"
dynamic = ["entry-points", "version"]

[tool.poetry]
include = [{path = "ots_eventcalendar_plugin/ui/**/*", format = ["sdist", "wheel"]}]
version = "0.0.0"

[tool.poetry.dependencies]
opentakserver = ">=1.7.0"
python = ">=3.10, <4.0"
icalendar = ">=6.0"

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
style = "semver"
dirty = false
pattern = "((?P<epoch>\\d+)!)?(?P<base>\\d+(\\.\\d+)*)"

[tool.poetry-dynamic-versioning.files."ots_eventcalendar_plugin/__init__.py"]
persistent-substitution = true
initial-content = """
  # These version placeholders will be replaced later during substitution.
  __version__ = "0.0.0"
  __version_tuple__ = (0, 0, 0)
"""

[build-system]
requires = ["poetry-core>=2.0.0", "poetry-dynamic-versioning>=1.0.0,<2.0.0", "setuptools"]
build-backend = "poetry_dynamic_versioning.backend"

[project.entry-points.'opentakserver.plugin']
ots_eventcalendar_plugin = 'ots_eventcalendar_plugin.app:EventCalendarPlugin'
